# Generated by Django 5.2.6 on 2025-09-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_ordermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
