# Generated by Django 5.2.6 on 2025-09-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
