# Generated by Django 5.2.6 on 2025-09-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_ordermodel_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_stock',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
