# Generated by Django 5.2.6 on 2025-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_product_size_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
