# Generated by Django 5.2.6 on 2025-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_ordermodel_delivered_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
