# Generated by Django 5.2.6 on 2025-09-20 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='address',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='houseNo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='society',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userregister'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orderDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
