# Generated by Django 5.2.6 on 2025-09-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_ordermodel_address_ordermodel_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='area',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='houseNo',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='society',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orderDate',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
