# Generated by Django 5.2.6 on 2025-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_coupon_ordermodel_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
