# Generated by Django 5.2.6 on 2025-10-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='label',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Other', 'Other')], default='Home', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userregister'),
        ),
    ]
