# Generated by Django 5.2.6 on 2026-03-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_remove_useraddress_address_useraddress_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_gram', models.DecimalField(decimal_places=2, help_text='Gold price per gram in INR', max_digits=10)),
                ('price_per_ounce', models.DecimalField(decimal_places=2, help_text='Gold price per ounce in USD', max_digits=10)),
                ('date', models.DateField(help_text='Date of the gold price')),
                ('time_updated', models.DateTimeField(help_text='Time when price was last updated')),
                ('source', models.CharField(choices=[('API', 'From Gold API'), ('MANUAL', 'Manual Entry')], default='API', help_text='Source of the gold price', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current price?')),
            ],
            options={
                'verbose_name_plural': 'Gold Prices',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_users', to='app1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='app1.userregister')),
            ],
            options={
                'verbose_name_plural': 'Watchlist Items',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
