# Generated by Django 5.2.6 on 2026-03-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_goldprice_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gold_weight_grams',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Gold weight in grams (e.g., 2.5, 5, 10)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Making/labor charges', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Other costs like diamonds, stones', max_digits=10),
        ),
    ]
